#1) Combining a one and a two-dimensional NumPy Array

In [2]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([[4,5,6],
                 [7,8,9]])
res = np.concatenate((arr2,[arr1]),axis = 0)
print(res)

[[4 5 6]
 [7 8 9]
 [1 2 3]]


#2) Flatten a 2d numpy array into 1d array

In [3]:
arr = np.array([[1,2,3],
                [4,5,6]])
res = np.ravel(arr)
print(res)

[1 2 3 4 5 6]


#3) Reverse a numpy array

In [4]:
arr  = np.array([1,2,3,4,5,6,7,8,9])

print(arr[::-1])

[9 8 7 6 5 4 3 2 1]


#4) Practice operations like Get the maximum value from given array Get the minimum value from given array Find the number of rows and columns of a given array using NumPy Select the elements from a given array (each element and specific element) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy

In [ ]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])

print("The Maximum number is:",arr.max(),'\n')
print("The Minimum number is:",arr.min(),'\n')
print("The shape of the array is:",arr.shape,'\n')
print("The array is :",arr[::1],'\n')
print("The number selected from the array is:",arr[1,2],'\n')
total = 0

for row in arr:
    for value in row:
        total += value

print("Final Sum =", total,'\n')

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[6, 5, 4],
              [3, 2, 1]])

print("Addition:")
print(a + b)

print("\nSubtraction:")
print(a - b)

print("\nMultiplication:")
print(a * b)

print("\nDivision:")
print(a / b)

    

The Maximum number is: 8 

The Minimum number is: 1 

The shape of the array is: (2, 4) 

The array is : [[1 2 3 4]
 [5 6 7 8]] 

The number selected from the array is: 7 

Final Sum = 36 

Addition:
[[7 7 7]
 [7 7 7]]

Subtraction:
[[-5 -3 -1]
 [ 1  3  5]]

Multiplication:
[[ 6 10 12]
 [12 10  6]]

Division:
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


#5) Iterate 3D array using for loop and nditer

In [38]:
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Using for loops:")

for block in arr:
    for row in block:
        for value in row:
            print(value)

print("\nUsing nditer:")

for value in np.nditer(arr):
    print(value)

Using for loops:
1
2
3
4
5
6
7
8

Using nditer:
1
2
3
4
5
6
7
8


#6) Study the following program import numpy as np # create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) # find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) -> Calculate average mean median mode values of two NumPy 2d-arrays

In [39]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[6, 5, 4],
                 [3, 2, 1]])

avg = (arr1 + arr2) / 2

print("Average Array:")
print(avg)

mean_value = np.mean(avg)
print("\nMean =", mean_value)

median_value = np.median(avg)
print("Median =", median_value)


flat = avg.flatten()

unique, counts = np.unique(flat, return_counts=True)

mode_value = unique[np.argmax(counts)]

print("Mode =", mode_value)

Average Array:
[[3.5 3.5 3.5]
 [3.5 3.5 3.5]]

Mean = 3.5
Median = 3.5
Mode = 3.5
