#1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]]

In [4]:
import numpy as np

arr = np.array([[6,-8,73,-110],
                [np.nan,-8,0,94]])

print(arr,'\n')

arr = np.nan_to_num(arr,nan = 0)
print(arr,'\n')

arr[[0,1]] = arr[[1,0]]
print(arr,'\n')

arr[:,[0,2]] = arr[:,[2,0]]
arr[:,[1,3]] = arr[:,[3,1]]
print(arr,'\n')

[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]] 

[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]] 

[[   0.   -8.    0.   94.]
 [   6.   -8.   73. -110.]] 

[[   0.   94.    0.   -8.]
 [  73. -110.    6.   -8.]] 



#2) Move axes of 3D array to new positions 

In [7]:
arr = np.array([[[1,2],
                 [3,4]],
                 [[5,6],
                  [7,8]]])
print("Original Array:\n")
print(arr,'\n')
print("Original Shape:\n")
print(arr.shape,'\n')
new_arr = np.moveaxis(arr,0,2)
print("New Array:\n")
print(new_arr,'\n')
print("New Shape:\n")
print(new_arr.shape)


Original Array:

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

Original Shape:

(2, 2, 2) 

New Array:

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]] 

New Shape:

(2, 2, 2)


#3) Replace NaN values with average of columns 

In [9]:
arr = np.array([[10, 20, np.nan],
                [40, np.nan, 60],
                [70, 80, 90]])

print("Original Array:")
print(arr)

col_mean = np.nanmean(arr, axis=0)

res = np.where(np.isnan(arr))
arr[res] = np.take(col_mean, res[1])

print("\nArray after replacing NaN with column averages:")
print(arr)

Original Array:
[[10. 20. nan]
 [40. nan 60.]
 [70. 80. 90.]]

Array after replacing NaN with column averages:
[[10. 20. 75.]
 [40. 50. 60.]
 [70. 80. 90.]]


#4) Replace negative value with zero in numpy array using replace

In [11]:
arr = np.array([10, -5, 20, -8, 15, -2])

print("Original Array:")
print(arr)

arr = np.where(arr < 0, 0, arr)

print("\nArray after replacing negative values with 0:")
print(arr)

Original Array:
[10 -5 20 -8 15 -2]

Array after replacing negative values with 0:
[10  0 20  0 15  0]
